# Generated by Django 5.1 on 2024-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regnumber',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
